/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Company Name

  @File Name
    filename.h

  @Summary
    Brief description of the file.

  @Description
    Describe the purpose of this file.
 */
/* ************************************************************************** */

#ifndef _XPMS_H    /* Guard against multiple inclusion */
#define _XPMS_H


/* ************************************************************************** */
/* ************************************************************************** */
/* Section: Included Files                                                    */
/* ************************************************************************** */
/* ************************************************************************** */

/* This section lists the other files that are included in this file.
 */

/* TODO:  Include other files here if needed. */


/* Provide C++ Compatibility */
#ifdef __cplusplus
extern "C" {
#endif

//chan1_R160.00.xpm
/* XPM */
/* width height ncolors chars_per_pixel */
//"41 41 2 1",
/* colors */
//"F c #000000",
//"B c #ffffff",
/* pixels */
static const uint8_t chan1a_xpm[] = \
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBFFFFFFFBBFBFBBBFFBFFBFFBFFFBBBBFBBFFFFFFFBBBBE"\
"BBBBFBBBBBFBBFFFBFFBFBFFBFFBFFFBBFBBFBFBBBBBFBBBBE"\
"BBBBFBFFFBFBBFFFFBFFBFFFBBBFBFBFBBFFFBFBFFFBFBBBBE"\
"BBBBFBFFFBFBBFBFBFBBBBBFFBFBBBBBBFFBBBFBFFFBFBBBBE"\
"BBBBFBFFFBFBFFBBFBBFBFFBBBFFFFFBFFFFFBFBFFFBFBBBBE"\
"BBBBFBBBBBFBBFFFFBFFBFFFFBFBFFFBBBBFFBFBBBBBFBBBBE"\
"BBBBFFFFFFFBFBFBFBFBFBFBFBFBFBFBFBFBFBFFFFFFFBBBBE"\
"BBBBBBBBBBBBFBFFBFBFBBFBBFBBBBFFBFBFBBBBBBBBBBBBBE"\
"BBBBBBFFBBFFFBFBBBBBFBBBFBBFBBFBFFFBFFFBFBBBBBBBBE"\
"BBBBBFFFFBBBFBBBFBBBBFBFBBBFBBBBFFFFFFFFFBFFFBBBBE"\
"BBBBBFFBBBFFFFFBFBBBBFBFBBBFFFFBFBFBBFBFBBFFBBBBBE"\
"BBBBFBBBFBBFFBFBBFFFFBBBFBFFBFFFFBFBFFFBBBBBBBBBBE"\
"BBBBBBFFBBFBFBFFBBFBBFFFBFFBBBFFBFBFFBBBBFFBBBBBBE"\
"BBBBBBBFFFBBBFBFFBFBBFBFBFBBFBFBBBFFFBFBBBFBBBBBBE"\
"BBBBFFBBFFFBBBBBFBFBFFFBBBFBBFFBBBFFFBFFBFBFFBBBBE"\
"BBBBFBFBFBBFFFFBBFFFBFFBBBFBBFBFFBBBFBFBFFBBBBBBBE"\
"BBBBFFBFBFFFBBBBFFBBBFFFBBBBBFBBBFFFFBBBFFBFFBBBBE"\
"BBBBFFBFFFBBBFFFFFFBFFBBBBBFFFBFBBBBFFBFBFBFBBBBBE"\
"BBBBFFFFBFFFFFBBFFFBBBBFBFFFFFBFFBBBFBFBFFFBBBBBBE"\
"BBBBBFFBBBBBBFFBBBBBBFFBFBFBBBFBBFFBFBFFBFFFBBBBBE"\
"BBBBFFFBFBFBFFFFFFBBFBBBFBBFBFFBFFBBBBFFFBFBFBBBBE"\
"BBBBBFFFBFBBBBBFBFFBBBFBBBBFFBFFFFBFFFFFFBBFFBBBBE"\
"BBBBBBBFBFFFFBFBBBFBBBFBBFFFBFBBFBFBBBFBFFFFBBBBBE"\
"BBBBFBBFFBBBFBBBFBBFFBBFFBBFBBBFBBFFBFFFFBBBBBBBBE"\
"BBBBBBBBBBFBBFFFFBBBFFFBFFFFBFBBFFBFBFBFBBFFFBBBBE"\
"BBBBFBBFBFBBBFBFFBBFFBBFFFBBFFBFFFFFFFFFBFFBFBBBBE"\
"BBBBFFBFBFFBBBBFFBBFBBFFFBBFBFBBFBBFFFBBFFBBFBBBBE"\
"BBBBFBFBBFBFFFFFBFBFFBBFFFFBBFFBFBBFFFFFFFBBBBBBBE"\
"BBBBFFFFFBFBFBBBFFFFFFBFBFBFBBBFFBFFBFBFFFBBBBBBBE"\
"BBBBBBBBFBBBFFBBBFFFFFFFBBFFBBFFFBFBBFBFBFBBFBBBBE"\
"BBBBFBBFBBFFFBBBBFFFFFBBBBFBFBBFBFFBBFFFBFFBBBBBBE"\
"BBBBBBBFFBBBFBFBBBFFFFBBFFFBFFFBBFFBBBFFBFFFBBBBBE"\
"BBBBBFFBFBFBBFBFBBFFFBBFFFBFBBBFFFFFFFFFFFFFBBBBBE"\
"BBBBBBBBBBBBFBFBFFFBFBBBBBFFBFBBFFFBFBBBFBFFFBBBBE"\
"BBBBFFFFFFFBFFFBFBBFBBFBBFBFBFBBBFBFFBFBFFFFBBBBBE"\
"BBBBFBBBBBFBBFBBFFFBFBFFFBFBFBBBFBFBFBBBFBBBBBBBBE"\
"BBBBFBFFFBFBBBBBBBFBFBFBFFBFFFBBBFFBFFFFFFFBFBBBBE"\
"BBBBFBFFFBFBFFFFBFFBBFFFFFFFBBBFBFFFBBBBFFBFFBBBBE"\
"BBBBFBFFFBFBFBFFFFBFBBBFBBFFBBFBFFBBFBBFBBBBFBBBBE"\
"BBBBFBBBBBFBBFBFFBFBFFBFBBBFFBFBBBBBFBFBFFBFBBBBBE"\
"BBBBFFFFFFFBBBFBFFBBBFFBFBFBBBFBBBBFFBFBBBBFBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE";

/* XPM */
static const char *const chan2_xpm[] = {
/* width height ncolors chars_per_pixel */
"37 37 2 1",
/* colors */
"F c #000000",
"B c #ffffff",
/* pixels */
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBFFFFFFFBFFFFBFFFBFBBFFFFBBFFFFFFFBB",
"BBFBBBBBFBBBBFFFFFBFFFFFBBBBFBBBBBFBB",
"BBFBFFFBFBBFBFBFFBBBFBFFBFBBFBFFFBFBB",
"BBFBFFFBFBBBFFBBFFBFFFFBBFFBFBFFFBFBB",
"BBFBFFFBFBBBFFFFBFBFFFBBBBFBFBFFFBFBB",
"BBFBBBBBFBBFBFBFFBBBBBFBBFFBFBBBBBFBB",
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBB",
"BBBBBBBBBBFFBBFBFBBBFFFBFFFBBBBBBBBBB",
"BBFFBFFBFBBFBBFFFFFFBFBFBBBBFBBBBBFBB",
"BBBBFBFBBBBBFBBBFBBBFFBFFFBFBFFBFFBBB",
"BBBFBBFBFBFFBBFBFBBFFBFFFFBBFBBBBFFBB",
"BBFFBFFBBBBBBBBBFFBFBBBBBFFBBBFFFBBBB",
"BBFBBFFBFBFFFBBFFBFBBBFFBFBBFFBBBFFBB",
"BBFBFFFBBFBFFBFBBBBFFBBBBFBBBFBBBBBBB",
"BBBFBFBBFBFFBBBBFFFBBFFBFBBFBFBBBBBBB",
"BBBBFFBBBBFBFBFFFBBBBFFBBFBFBFBBFBFBB",
"BBBFBBFFFFFBFFFBBFBBBBFBFBFFFFFFBFFBB",
"BBFFFBBFBFBBBFBBBFBBFBFFBBFBFFFBBFFBB",
"BBBBFFBBFBBBFBFFFFFBBFBFFFBFFBBBBBFBB",
"BBBFFBFFBFFFBFBFBBBBBFBBFFBBBBBBFFFBB",
"BBFFFBFFFFBFFFBFBFFFBBFBBFFBBBBBBBBBB",
"BBFFFFFBBBBFFBFFBBFBBFFBBFBBBFFFBFBBB",
"BBFBBBFBFFFFBFBFBBBFBBFBFFBBFFFBBFFBB",
"BBFBFFBBBFBFFFFFBBBFBBFBFFFFBFBBFBBBB",
"BBFFBFBFFFFBFFFFBFBBBFFBFBFFFFFBBFBBB",
"BBBBBBBBBBFBFBBFFBBFFBBBFBFBBBFBFFBBB",
"BBFFFFFFFBBFFFFFBFFFBFFFFFFBFBFBFBBBB",
"BBFBBBBBFBBBFFBBBBFBFBFBFFFBBBFFFBFBB",
"BBFBFFFBFBFFBBBBFFFBBFFBFFFFFFFFBFFBB",
"BBFBFFFBFBFBFFFFFBFFBFFFFFBFBBBBBFFBB",
"BBFBFFFBFBBFFFBBBFBFBFBFFBBFBFFBBFFBB",
"BBFBBBBBFBFBBBFBFBFBFBBBFBBBBFFFFFFBB",
"BBFFFFFFFBFFBBFFFBBFFBFBFBFFFFFFBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};

/* XPM */
static const char *const chan3_xpm[] = {
/* width height ncolors chars_per_pixel */
"37 37 2 1",
/* colors */
"F c #000000",
"B c #ffffff",
/* pixels */
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBFFFFFFFBBBFBBBFBBBBFFBFBBBFFFFFFFBB",
"BBFBBBBBFBBFBBBFBBBBBFBBBFFBFBBBBBFBB",
"BBFBFFFBFBFBBFBBBFBBBFBBBFBBFBFFFBFBB",
"BBFBFFFBFBBFBBFFBBFBBBBFFBBBFBFFFBFBB",
"BBFBFFFBFBBFBBFFBBFBFFBFFFFBFBFFFBFBB",
"BBFBBBBBFBBBFFFBFFFBFFFFFFBBFBBBBBFBB",
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBB",
"BBBBBBBBBBFBBFBBBFBFBFBFFBBBBBBBBBBBB",
"BBFFFBFFFFFBBBFBBBFFBBFBBBBFFBBBFBBBB",
"BBFBBBFFBFFFBFFFBFFFBBFBBBFBFBBFBBFBB",
"BBFFFFBBFBFBFFFBFFFBFBFBBBBBFFFFBFFBB",
"BBBFBFFBBFBFFBFFFBFFFFBFFFBFBFBFBFBBB",
"BBBFFFBBFFFBFFBBFFFFBFFBBBBFFBBFBBFBB",
"BBFFBBBFBFFFFFBBFFBBBBFFBBFBFBBFFBFBB",
"BBBBBBFBFBFFBBBFBBFBBBBFFBBBFBBBBFFBB",
"BBBBFBBBBFBBBFBBBFBFFBBFFBFBFBFFBFBBB",
"BBBBFFFBFBFBFBFBBFFFBBFFBFFFFBBBBFFBB",
"BBBBFBFBBFBFFFFFBFFBBFFBFBBFFBBBFBFBB",
"BBFBFBBFFFBFFFFBFBBFBBBBFBBBFFBFBFFBB",
"BBBBFBBFBBFBBBFFFBBFFFFFFBFBFFBFBFBBB",
"BBFBFFFBFBFBBFBBFBBFBFBFBFFFFFBBBFFBB",
"BBBFFBBBBBFBFFBBFFBFFBBFFBFFFBBBFBFBB",
"BBFBBFFBFBBFFBBFBBBBBBFFBBBBFBBFBFFBB",
"BBBFFBFFBFBBFFBBBFFFFFFFBFBBBBFBBFBBB",
"BBFBFBBFFFBBFBFBBBBFBBFFFFFFFFFFBBBBB",
"BBBBBBBBBBFFFFFFBFBBBBFFFFFBBBFFBFFBB",
"BBFFFFFFFBFFFFFBFBFFBBBBFFFBFBFBFFFBB",
"BBFBBBBBFBFBFBFFFFBFBFBFBBFBBBFBBFBBB",
"BBFBFFFBFBFFBFBBFBBFBFFFBBFFFFFBBFFBB",
"BBFBFFFBFBBBFFBBFFBFFBFBBFFBBFFBFBFBB",
"BBFBFFFBFBFBBBBFBBBBBBBBFFBBBBFFBBFBB",
"BBFBBBBBFBFFFFBBBFFFBBFFFFFBFBFBBFBBB",
"BBFFFFFFFBFBFBFBBFBFFFBFFBFBBBFFBFFBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};

/* XPM */
static const char *const chan4_xpm[] = {
/* width height ncolors chars_per_pixel */
"37 37 2 1",
/* colors */
"F c #000000",
"B c #ffffff",
/* pixels */
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBFFFFFFFBBBFBBBFBBBBFFBFBBBFFFFFFFBB",
"BBFBBBBBFBBFBBBFBBBFFFBBBFFBFBBBBBFBB",
"BBFBFFFBFBFBBFBBBFBBFFBBBFBBFBFFFBFBB",
"BBFBFFFBFBBFBBFFBBFBBBBFFBBBFBFFFBFBB",
"BBFBFFFBFBBFBBFFBBFBFFBFFFFBFBFFFBFBB",
"BBFBBBBBFBBBFFFBFFFBFFFFFFBBFBBBBBFBB",
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBB",
"BBBBBBBBBBFBBFBBBFBFBFBFFBBBBBBBBBBBB",
"BBFFFBFFFFFBBBFBBBFFBBFBBBBFFBBBFBBBB",
"BBFBBBBFBBFFBFFFBFFFBBFBBBFBFBBFBBFBB",
"BBFFBFFBFFBBFFFBFFFBFBFBBBBBFFFFBFFBB",
"BBFFFBFBBFFFFBFFFBFFFFBFFFBFBFBFBFBBB",
"BBBFBBFFFFBBFFBBFFFFBFFBBBBFFBBFBBFBB",
"BBFFBFBFBBBBFFBBFFBBBBFFBBFBFBBFFBFBB",
"BBBFBBFBFBFFBBBFBBFBBBBFFBBBFBBBBFFBB",
"BBFBFFBBBFBFFFBBBFFFFBBFFBFBFBFFBFBBB",
"BBBBBFBBFFFFFBFBBBFFBBFFBFFFFBBBBFFBB",
"BBFFFBFBBFFBBFFFBBFBBFFBFBBFFBBBFBFBB",
"BBFFBFBBFBBBBFFBFBBFBBBBFBBBFFBFBFFBB",
"BBBBBFFBBFFFBBFFFFFFFFFFFBFBFFBFBFBBB",
"BBBFBBBBFFBFFFBBFBFFBFBFBFFFFFBBBFFBB",
"BBBBFFBBBFBFFFBBFBFFFBBFFBFFFBBBFBFBB",
"BBFBFFFFFBBFFBBFBBFBBBFFBBBBFBBFBFFBB",
"BBBFFFBFBBBBFFBBBFFFFFFFBFBBBBFBBFBBB",
"BBFBFBFBFBFFFBFBBBBFBBFFFFFFFFFFBBBBB",
"BBBBBBBBBBFBBFFFBFBBBBFFFFFBBBFFBFFBB",
"BBFFFFFFFBFFFFFBFBFFBBBBFFFBFBFBFFFBB",
"BBFBBBBBFBFFFBFFFFBFBFBFBBFBBBFBBFBBB",
"BBFBFFFBFBFBBFBBFBBFBFFFBBFFFFFBBFFBB",
"BBFBFFFBFBBFFFBBFFBFFBFBBFFBBFFBFBFBB",
"BBFBFFFBFBFBFBBFBBBBBBBBFFBBBBFFBBFBB",
"BBFBBBBBFBFFFFBBBFFFBBFFFFFBFBFBBFBBB",
"BBFFFFFFFBFBFBFBBFBFFFBFFBFBBBFFBFFBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};



    /* Provide C++ Compatibility */
#ifdef __cplusplus
}
#endif

#endif /* _XPMS_H */

/* *****************************************************************************
 End of File
 */
