/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Company Name

  @File Name
    filename.h

  @Summary
    Brief description of the file.

  @Description
    Describe the purpose of this file.
 */
/* ************************************************************************** */

#ifndef _XPMS_H    /* Guard against multiple inclusion */
#define _XPMS_H

#include <xc.h>
/* ************************************************************************** */
/* ************************************************************************** */
/* Section: Included Files                                                    */
/* ************************************************************************** */
/* ************************************************************************** */

/* This section lists the other files that are included in this file.
 */

/* TODO:  Include other files here if needed. */


/* Provide C++ Compatibility */
#ifdef __cplusplus
extern "C" { 
#endif
static const uint8_t chan1a_txt[]  = "Channel 1";
static const uint8_t chan1a_ptic[] = "Price R159.85";
//channel 1_R160.00.xpm https://pos.snapscan.io/qr/CMMCyv0i?id=Chan1&amount=15985
/* XPM */
/* width height ncolors chars_per_pixel */
//"41 41 2 1",
/* colors */
//"F c #000000",
//"B c #ffffff",
/* pixels */
//mediumconst  00E8BD
//__end_of_chan1a_txt@xpms$F3551                  mediumconst  00F299
//__end_of_chan1a_xpm                             mediumconst  00F250
//_chan1a_xpm             MEDIUMCONST     E8BD    0000    2451
//_chan1a_xpm@xpms$F3553          MEDIUMCONST     0000    0000    0
//
#if 0
static const uint8_t chan1a_xpm[] = \
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBFFFFFFFBBFBFBBBFFBFFBFFBFFFBBBBFBBFFFFFFFBBBBE"\
"BBBBFBBBBBFBBFFFBFFBFBFFBFFBFFFBBFBBFBFBBBBBFBBBBE"\
"BBBBFBFFFBFBBFFFFBFFBFFFBBBFBFBFBBFFFBFBFFFBFBBBBE"\
"BBBBFBFFFBFBBFBFBFBBBBBFFBFBBBBBBFFBBBFBFFFBFBBBBE"\
"BBBBFBFFFBFBFFBBFBBFBFFBBBFFFFFBFFFFFBFBFFFBFBBBBE"\
"BBBBFBBBBBFBBFFFFBFFBFFFFBFBFFFBBBBFFBFBBBBBFBBBBE"\
"BBBBFFFFFFFBFBFBFBFBFBFBFBFBFBFBFBFBFBFFFFFFFBBBBE"\
"BBBBBBBBBBBBFBFFBFBFBBFBBFBBBBFFBFBFBBBBBBBBBBBBBE"\
"BBBBBBFFBBFFFBFBBBBBFBBBFBBFBBFBFFFBFFFBFBBBBBBBBE"\
"BBBBBFFFFBBBFBBBFBBBBFBFBBBFBBBBFFFFFFFFFBFFFBBBBE"\
"BBBBBFFBBBFFFFFBFBBBBFBFBBBFFFFBFBFBBFBFBBFFBBBBBE"\
"BBBBFBBBFBBFFBFBBFFFFBBBFBFFBFFFFBFBFFFBBBBBBBBBBE"\
"BBBBBBFFBBFBFBFFBBFBBFFFBFFBBBFFBFBFFBBBBFFBBBBBBE"\
"BBBBBBBFFFBBBFBFFBFBBFBFBFBBFBFBBBFFFBFBBBFBBBBBBE"\
"BBBBFFBBFFFBBBBBFBFBFFFBBBFBBFFBBBFFFBFFBFBFFBBBBE"\
"BBBBFBFBFBBFFFFBBFFFBFFBBBFBBFBFFBBBFBFBFFBBBBBBBE"\
"BBBBFFBFBFFFBBBBFFBBBFFFBBBBBFBBBFFFFBBBFFBFFBBBBE"\
"BBBBFFBFFFBBBFFFFFFBFFBBBBBFFFBFBBBBFFBFBFBFBBBBBE"\
"BBBBFFFFBFFFFFBBFFFBBBBFBFFFFFBFFBBBFBFBFFFBBBBBBE"\
"BBBBBFFBBBBBBFFBBBBBBFFBFBFBBBFBBFFBFBFFBFFFBBBBBE"\
"BBBBFFFBFBFBFFFFFFBBFBBBFBBFBFFBFFBBBBFFFBFBFBBBBE"\
"BBBBBFFFBFBBBBBFBFFBBBFBBBBFFBFFFFBFFFFFFBBFFBBBBE"\
"BBBBBBBFBFFFFBFBBBFBBBFBBFFFBFBBFBFBBBFBFFFFBBBBBE"\
"BBBBFBBFFBBBFBBBFBBFFBBFFBBFBBBFBBFFBFFFFBBBBBBBBE"\
"BBBBBBBBBBFBBFFFFBBBFFFBFFFFBFBBFFBFBFBFBBFFFBBBBE"\
"BBBBFBBFBFBBBFBFFBBFFBBFFFBBFFBFFFFFFFFFBFFBFBBBBE"\
"BBBBFFBFBFFBBBBFFBBFBBFFFBBFBFBBFBBFFFBBFFBBFBBBBE"\
"BBBBFBFBBFBFFFFFBFBFFBBFFFFBBFFBFBBFFFFFFFBBBBBBBE"\
"BBBBFFFFFBFBFBBBFFFFFFBFBFBFBBBFFBFFBFBFFFBBBBBBBE"\
"BBBBBBBBFBBBFFBBBFFFFFFFBBFFBBFFFBFBBFBFBFBBFBBBBE"\
"BBBBFBBFBBFFFBBBBFFFFFBBBBFBFBBFBFFBBFFFBFFBBBBBBE"\
"BBBBBBBFFBBBFBFBBBFFFFBBFFFBFFFBBFFBBBFFBFFFBBBBBE"\
"BBBBBFFBFBFBBFBFBBFFFBBFFFBFBBBFFFFFFFFFFFFFBBBBBE"\
"BBBBBBBBBBBBFBFBFFFBFBBBBBFFBFBBFFFBFBBBFBFFFBBBBE"\
"BBBBFFFFFFFBFFFBFBBFBBFBBFBFBFBBBFBFFBFBFFFFBBBBBE"\
"BBBBFBBBBBFBBFBBFFFBFBFFFBFBFBBBFBFBFBBBFBBBBBBBBE"\
"BBBBFBFFFBFBBBBBBBFBFBFBFFBFFFBBBFFBFFFFFFFBFBBBBE"\
"BBBBFBFFFBFBFFFFBFFBBFFFFFFFBBBFBFFFBBBBFFBFFBBBBE"\
"BBBBFBFFFBFBFBFFFFBFBBBFBBFFBBFBFFBBFBBFBBBBFBBBBE"\
"BBBBFBBBBBFBBFBFFBFBFFBFBBBFFBFBBBBBFBFBFFBFBBBBBE"\
"BBBBFFFFFFFBBBFBFFBBBFFBFBFBBBFBBBBFFBFBBBBFBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE";
#endif
/* XPM */
//static const char *const chan2_xpm[] = {
/* width height ncolors chars_per_pixel */
//"37 37 2 1",
/* colors */
//"F c #000000",
//"B c #ffffff",
static const uint8_t chan2_xpm[] = {
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBFFFFFFFBFFFFBFFFBFBBFFFFBBFFFFFFFBBE"\
"BBFBBBBBFBBBBFFFFFBFFFFFBBBBFBBBBBFBBE"\
"BBFBFFFBFBBFBFBFFBBBFBFFBFBBFBFFFBFBBE"\
"BBFBFFFBFBBBFFBBFFBFFFFBBFFBFBFFFBFBBE"\
"BBFBFFFBFBBBFFFFBFBFFFBBBBFBFBFFFBFBBE"\
"BBFBBBBBFBBFBFBFFBBBBBFBBFFBFBBBBBFBBE"\
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBBE"\
"BBBBBBBBBBFFBBFBFBBBFFFBFFFBBBBBBBBBBE"\
"BBFFBFFBFBBFBBFFFFFFBFBFBBBBFBBBBBFBBE"\
"BBBBFBFBBBBBFBBBFBBBFFBFFFBFBFFBFFBBBE"\
"BBBFBBFBFBFFBBFBFBBFFBFFFFBBFBBBBFFBBE"\
"BBFFBFFBBBBBBBBBFFBFBBBBBFFBBBFFFBBBBE"\
"BBFBBFFBFBFFFBBFFBFBBBFFBFBBFFBBBFFBBE"\
"BBFBFFFBBFBFFBFBBBBFFBBBBFBBBFBBBBBBBE"\
"BBBFBFBBFBFFBBBBFFFBBFFBFBBFBFBBBBBBBE"\
"BBBBFFBBBBFBFBFFFBBBBFFBBFBFBFBBFBFBBE"\
"BBBFBBFFFFFBFFFBBFBBBBFBFBFFFFFFBFFBBE"\
"BBFFFBBFBFBBBFBBBFBBFBFFBBFBFFFBBFFBBE"\
"BBBBFFBBFBBBFBFFFFFBBFBFFFBFFBBBBBFBBE"\
"BBBFFBFFBFFFBFBFBBBBBFBBFFBBBBBBFFFBBE"\
"BBFFFBFFFFBFFFBFBFFFBBFBBFFBBBBBBBBBBE"\
"BBFFFFFBBBBFFBFFBBFBBFFBBFBBBFFFBFBBBE"\
"BBFBBBFBFFFFBFBFBBBFBBFBFFBBFFFBBFFBBE"\
"BBFBFFBBBFBFFFFFBBBFBBFBFFFFBFBBFBBBBE"\
"BBFFBFBFFFFBFFFFBFBBBFFBFBFFFFFBBFBBBE"\
"BBBBBBBBBBFBFBBFFBBFFBBBFBFBBBFBFFBBBE"\
"BBFFFFFFFBBFFFFFBFFFBFFFFFFBFBFBFBBBBE"\
"BBFBBBBBFBBBFFBBBBFBFBFBFFFBBBFFFBFBBE"\
"BBFBFFFBFBFFBBBBFFFBBFFBFFFFFFFFBFFBBE"\
"BBFBFFFBFBFBFFFFFBFFBFFFFFBFBBBBBFFBBE"\
"BBFBFFFBFBBFFFBBBFBFBFBFFBBFBFFBBFFBBE"\
"BBFBBBBBFBFBBBFBFBFBFBBBFBBBBFFFFFFBBE"\
"BBFFFFFFFBFFBBFFFBBFFBFBFBFFFFFFBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"};
/*"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"\
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"\
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"*/

/* XPM */
static const char *const chan3_xpm[] = {
/* width height ncolors chars_per_pixel */
"37 37 2 1",
/* colors */
"F c #000000",
"B c #ffffff",
/* pixels */
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBFFFFFFFBBBFBBBFBBBBFFBFBBBFFFFFFFBB"\
"BBFBBBBBFBBFBBBFBBBBBFBBBFFBFBBBBBFBB"\
"BBFBFFFBFBFBBFBBBFBBBFBBBFBBFBFFFBFBB"\
"BBFBFFFBFBBFBBFFBBFBBBBFFBBBFBFFFBFBB"\
"BBFBFFFBFBBFBBFFBBFBFFBFFFFBFBFFFBFBB"\
"BBFBBBBBFBBBFFFBFFFBFFFFFFBBFBBBBBFBB"\
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBB"\
"BBBBBBBBBBFBBFBBBFBFBFBFFBBBBBBBBBBBB"\
"BBFFFBFFFFFBBBFBBBFFBBFBBBBFFBBBFBBBB"\
"BBFBBBFFBFFFBFFFBFFFBBFBBBFBFBBFBBFBB"\
"BBFFFFBBFBFBFFFBFFFBFBFBBBBBFFFFBFFBB"\
"BBBFBFFBBFBFFBFFFBFFFFBFFFBFBFBFBFBBB"\
"BBBFFFBBFFFBFFBBFFFFBFFBBBBFFBBFBBFBB"\
"BBFFBBBFBFFFFFBBFFBBBBFFBBFBFBBFFBFBB"\
"BBBBBBFBFBFFBBBFBBFBBBBFFBBBFBBBBFFBB"\
"BBBBFBBBBFBBBFBBBFBFFBBFFBFBFBFFBFBBB"\
"BBBBFFFBFBFBFBFBBFFFBBFFBFFFFBBBBFFBB"\
"BBBBFBFBBFBFFFFFBFFBBFFBFBBFFBBBFBFBB"\
"BBFBFBBFFFBFFFFBFBBFBBBBFBBBFFBFBFFBB"\
"BBBBFBBFBBFBBBFFFBBFFFFFFBFBFFBFBFBBB"\
"BBFBFFFBFBFBBFBBFBBFBFBFBFFFFFBBBFFBB"\
"BBBFFBBBBBFBFFBBFFBFFBBFFBFFFBBBFBFBB"\
"BBFBBFFBFBBFFBBFBBBBBBFFBBBBFBBFBFFBB"\
"BBBFFBFFBFBBFFBBBFFFFFFFBFBBBBFBBFBBB"\
"BBFBFBBFFFBBFBFBBBBFBBFFFFFFFFFFBBBBB"\
"BBBBBBBBBBFFFFFFBFBBBBFFFFFBBBFFBFFBB"\
"BBFFFFFFFBFFFFFBFBFFBBBBFFFBFBFBFFFBB"\
"BBFBBBBBFBFBFBFFFFBFBFBFBBFBBBFBBFBBB"\
"BBFBFFFBFBFFBFBBFBBFBFFFBBFFFFFBBFFBB"\
"BBFBFFFBFBBBFFBBFFBFFBFBBFFBBFFBFBFBB"\
"BBFBFFFBFBFBBBBFBBBBBBBBFFBBBBFFBBFBB"\
"BBFBBBBBFBFFFFBBBFFFBBFFFFFBFBFBBFBBB"\
"BBFFFFFFFBFBFBFBBFBFFFBFFBFBBBFFBFFBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};

/* XPM */
static const char *const chan4_xpm[] = {
/* width height ncolors chars_per_pixel */
"37 37 2 1",
/* colors */
"F c #000000",
"B c #ffffff",
/* pixels */
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBFFFFFFFBBBFBBBFBBBBFFBFBBBFFFFFFFBB"\
"BBFBBBBBFBBFBBBFBBBFFFBBBFFBFBBBBBFBB"\
"BBFBFFFBFBFBBFBBBFBBFFBBBFBBFBFFFBFBB"\
"BBFBFFFBFBBFBBFFBBFBBBBFFBBBFBFFFBFBB"\
"BBFBFFFBFBBFBBFFBBFBFFBFFFFBFBFFFBFBB"\
"BBFBBBBBFBBBFFFBFFFBFFFFFFBBFBBBBBFBB"\
"BBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBB"\
"BBBBBBBBBBFBBFBBBFBFBFBFFBBBBBBBBBBBB"\
"BBFFFBFFFFFBBBFBBBFFBBFBBBBFFBBBFBBBB"\
"BBFBBBBFBBFFBFFFBFFFBBFBBBFBFBBFBBFBB"\
"BBFFBFFBFFBBFFFBFFFBFBFBBBBBFFFFBFFBB"\
"BBFFFBFBBFFFFBFFFBFFFFBFFFBFBFBFBFBBB"\
"BBBFBBFFFFBBFFBBFFFFBFFBBBBFFBBFBBFBB"\
"BBFFBFBFBBBBFFBBFFBBBBFFBBFBFBBFFBFBB"\
"BBBFBBFBFBFFBBBFBBFBBBBFFBBBFBBBBFFBB"\
"BBFBFFBBBFBFFFBBBFFFFBBFFBFBFBFFBFBBB"\
"BBBBBFBBFFFFFBFBBBFFBBFFBFFFFBBBBFFBB"\
"BBFFFBFBBFFBBFFFBBFBBFFBFBBFFBBBFBFBB"\
"BBFFBFBBFBBBBFFBFBBFBBBBFBBBFFBFBFFBB"\
"BBBBBFFBBFFFBBFFFFFFFFFFFBFBFFBFBFBBB"\
"BBBFBBBBFFBFFFBBFBFFBFBFBFFFFFBBBFFBB"\
"BBBBFFBBBFBFFFBBFBFFFBBFFBFFFBBBFBFBB"\
"BBFBFFFFFBBFFBBFBBFBBBFFBBBBFBBFBFFBB"\
"BBBFFFBFBBBBFFBBBFFFFFFFBFBBBBFBBFBBB"\
"BBFBFBFBFBFFFBFBBBBFBBFFFFFFFFFFBBBBB"\
"BBBBBBBBBBFBBFFFBFBBBBFFFFFBBBFFBFFBB"\
"BBFFFFFFFBFFFFFBFBFFBBBBFFFBFBFBFFFBB"\
"BBFBBBBBFBFFFBFFFFBFBFBFBBFBBBFBBFBBB"\
"BBFBFFFBFBFBBFBBFBBFBFFFBBFFFFFBBFFBB"\
"BBFBFFFBFBBFFFBBFFBFFBFBBFFBBFFBFBFBB"\
"BBFBFFFBFBFBFBBFBBBBBBBBFFBBBBFFBBFBB"\
"BBFBBBBBFBFFFFBBBFFFBBFFFFFBFBFBBFBBB"\
"BBFFFFFFFBFBFBFBBFBFFFBFFBFBBBFFBFFBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};


//chan1_R159.85.xpm
/* XPM */

/* width height ncolors chars_per_pixel */
//uint8_t xpm1_size[] = {"37 37 2 1",
/* colors */
//"F c #000000",
//"B c #ffffff",};
/* pixels */
const uint8_t qrstat1_xpm[] = "49 49 2 1";
const uint8_t qrcode1_xpm[] = {
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBFFFFFFFBBFBFBBBFFBFFBFFBFFFBBBBFBBFFFFFFFBBBBE"\
"BBBBFBBBBBFBBFFFBFFBFBFFBFFBFFFBBFBBFBFBBBBBFBBBBE"\
"BBBBFBFFFBFBBFFFFBFFBFFFBBBFBFBFBBFFFBFBFFFBFBBBBE"\
"BBBBFBFFFBFBBFBFBFBBBBBFFBFBBBBBBFFBBBFBFFFBFBBBBE"\
"BBBBFBFFFBFBFFBBFBBFBFFBBBFFFFFBFFFFFBFBFFFBFBBBBE"\
"BBBBFBBBBBFBBFFFFBFFBFFFFBFBFFFBBBBFFBFBBBBBFBBBBE"\
"BBBBFFFFFFFBFBFBFBFBFBFBFBFBFBFBFBFBFBFFFFFFFBBBBE"\
"BBBBBBBBBBBBFBFFBFBFBBFBBFBBBBFFBFBFBBBBBBBBBBBBBE"\
"BBBBBBFFBBFFFBFBBBBBFBBBFBBFBBFBFFFBFFFBFBBBBBBBBE"\
"BBBBBFFFFBBBFBBBFBBBBFBFBBBFBBBBFFFFFFFFFBFFFBBBBE"\
"BBBBBFFBBBFFFFFBFBBBBFBFBBBFFFFBFBFBBFBFBBFFBBBBBE"\
"BBBBFBBBFBBFFBFBBFFFFBBBFBFFBFFFFBFBFFFBBBBBBBBBBE"\
"BBBBBBFFBBFBFBFFBBFBBFFFBFFBBBFFBFBFFBBBBFFBBBBBBE"\
"BBBBBBBFFFBBBFBFFBFBBFBFBFBBFBFBBBFFFBFBBBFBBBBBBE"\
"BBBBFFBBFFFBBBBBFBFBFFFBBBFBBFFBBBFFFBFFBFBFFBBBBE"\
"BBBBFBFBFBBFFFFBBFFFBFFBBBFBBFBFFBBBFBFBFFBBBBBBBE"\
"BBBBFFBFBFFFBBBBFFBBBFFFBBBBBFBBBFFFFBBBFFBFFBBBBE"\
"BBBBFFBFFFBBBFFFFFFBFFBBBBBFFFBFBBBBFFBFBFBFBBBBBE"\
"BBBBFFFFBFFFFFBBFFFBBBBFBFFFFFBFFBBBFBFBFFFBBBBBBE"\
"BBBBBFFBBBBBBFFBBBBBBFFBFBFBBBFBBFFBFBFFBFFFBBBBBE"\
"BBBBFFFBFBFBFFFFFFBBFBBBFBBFBFFBFFBBBBFFFBFBFBBBBE"\
"BBBBBFFFBFBBBBBFBFFBBBFBBBBFFBFFFFBFFFFFFBBFFBBBBE"\
"BBBBBBBFBFFFFBFBBBFBBBFBBFFFBFBBFBFBBBFBFFFFBBBBBE"\
"BBBBFBBFFBBBFBBBFBBFFBBFFBBFBBBFBBFFBFFFFBBBBBBBBE"\
"BBBBBBBBBBFBBFFFFBBBFFFBFFFFBFBBFFBFBFBFBBFFFBBBBE"\
"BBBBFBBFBFBBBFBFFBBFFBBFFFBBFFBFFFFFFFFFBFFBFBBBBE"\
"BBBBFFBFBFFBBBBFFBBFBBFFFBBFBFBBFBBFFFBBFFBBFBBBBE"\
"BBBBFBFBBFBFFFFFBFBFFBBFFFFBBFFBFBBFFFFFFFBBBBBBBE"\
"BBBBFFFFFBFBFBBBFFFFFFBFBFBFBBBFFBFFBFBFFFBBBBBBBE"\
"BBBBBBBBFBBBFFBBBFFFFFFFBBFFBBFFFBFBBFBFBFBBFBBBBE"\
"BBBBFBBFBBFFFBBBBFFFFFBBBBFBFBBFBFFBBFFFBFFBBBBBBE"\
"BBBBBBBFFBBBFBFBBBFFFFBBFFFBFFFBBFFBBBFFBFFFBBBBBE"\
"BBBBBFFBFBFBBFBFBBFFFBBFFFBFBBBFFFFFFFFFFFFFBBBBBE"\
"BBBBBBBBBBBBFBFBFFFBFBBBBBFFBFBBFFFBFBBBFBFFFBBBBE"\
"BBBBFFFFFFFBFFFBFBBFBBFBBFBFBFBBBFBFFBFBFFFFBBBBBE"\
"BBBBFBBBBBFBBFBBFFFBFBFFFBFBFBBBFBFBFBBBFBBBBBBBBE"\
"BBBBFBFFFBFBBBBBBBFBFBFBFFBFFFBBBFFBFFFFFFFBFBBBBE"\
"BBBBFBFFFBFBFFFFBFFBBFFFFFFFBBBFBFFFBBBBFFBFFBBBBE"\
"BBBBFBFFFBFBFBFFFFBFBBBFBBFFBBFBFFBBFBBFBBBBFBBBBE"\
"BBBBFBBBBBFBBFBFFBFBFFBFBBBFFBFBBBBBFBFBFFBFBBBBBE"\
"BBBBFFFFFFFBBBFBFFBBBFFBFBFBBBFBBBBFFBFBBBBFBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBE"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"};


static const uint8_t mms_xpm[] = {
"/* XPM */chan1%159.85,"\
"/* width height ncolors chars_per_pixel */,"\
"39 39 2 1,"\
"/* colors */,"\
"F c #000000,"\
"B c #ffffff,"\
"/* pixels */,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB,"\
"BBBFFFFFFFBBFBFBFBFFBFFFFBFBBFFFFFFFBBB,"\
"BBBFBBBBBFBBFFFBFFFFBFBBBFBBBFBBBBBFBBB,"\
"BBBFBFFFBFBFBFFBFBFFBBFFFBFFBFBFFFBFBBB,"\
"BBBFBFFFBFBFBFBFBFBFFFFFBFBFBFBFFFBFBBB,"\
"BBBFBFFFBFBFFBBFFBFBFBFBBBFFBFBFFFBFBBB,"\
"BBBFBBBBBFBFFFFFBFFFBFBFBFBBBFBBBBBFBBB,"\
"BBBFFFFFFFBFBFBFBFBFBFBFBFBFBFFFFFFFBBB,"\
"BBBBBBBBBBBFBFBFBFFBBBBFFBBFBBBBBBBBBBB,"\
"BBBFBFFFFFBBBBFBBFFBFBFBBFBBBFFFFFBBBBB,"\
"BBBFBBFFBBBBFFBFBBFFBFFBFBFBBFFBFFFFBBB,"\
"BBBBFFFBBFBFFBBFBBFFBBBBFBBFFFBFBFBBBBB,"\
"BBBBBFBFFBBBBBBFBFBBBBFFFFFBFBBFFFBFBBB,"\
"BBBBFBBBFFBFBBFBBBFBFFFFBFFBFBBFFBFBBBB,"\
"BBBFBBFFBBFFFBBFFFFFFBFBFBFFBBFBBFFFBBB,"\
"BBBFFBBFFFBFBFFFFBBBFBBBFBBFFFFBBFFBBBB,"\
"BBBFFFFFBBBFBBFBBFBFBBBFFFFBFFBBFFBBBBB,"\
"BBBBFBFBBFBFBFBBFBBBFFBBBFFFFBFFBBBFBBB,"\
"BBBFBBBFBBFFBBBFBFFFFFFFBFFFFFFBFFFFBBB,"\
"BBBBBBFFBFFFBBFFBFFFBFBFFFBBBBFFBFFBBBB,"\
"BBBBFFBFBBBFFFBBFBBFBBBBFFFFFFFFFFFBBBB,"\
"BBBBBBFFFFBBFBBBBFBBFFBFBFBFFBFFFBBFBBB,"\
"BBBFBFFFBBFBBBFBBBFBFBFFFBFBBFBBBBBFBBB,"\
"BBBFBFFBFFFBFFBFBFFBFBBBFBBBBBBBFFFBBBB,"\
"BBBFBFFBFBBFBFFFBBBBBBFFFBBFBBFFBFBFBBB,"\
"BBBFBFFFFFFFFBBFBBBBFBFBBFBFFFFFFBBFBBB,"\
"BBBBBBBBBBBFBBFFFBBBFBFFBFFFBBBFBFFFBBB,"\
"BBBFFFFFFFBBFFFBFFFBBFBFBFFFBFBFBFFBBBB,"\
"BBBFBBBBBFBFBFBBFFBBBFFBFFFFBBBFFFFFBBB,"\
"BBBFBFFFBFBFFBFFBBFBFFBBBFBFFFFFFBBBBBB,"\
"BBBFBFFFBFBFFFBFBFFBBBFFFFFBFBBFFBFFBBB,"\
"BBBFBFFFBFBFFBFFFBFFBFBFBBFBBFFBFBBBBBB,"\
"BBBFBBBBBFBBFBBFFFFFBBBFFFBBBFBFFFBBBBB,"\
"BBBFFFFFFFBFFBBBBBFFFBBBBFFFBBFBBBFBBBB,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB};,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB};,"\
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\0"};






    /* Provide C++ Compatibility */
#ifdef __cplusplus
}
#endif

#endif /* _XPMS_H */

/* *****************************************************************************
 End of File
 */
